#version 450 core

layout (local_size_x = 16) in;

layout (rgba8ui, binding = 0) uniform uimageBuffer src;
layout (rgba8ui, binding = 1) uniform uimageBuffer dst;

// NOTE: this shader composite two layers together
void main(void) {
    int pix_id = int(gl_WorkGroupID.x * 16 + gl_LocalInvocationID.x);
    uvec4 col_src = imageLoad(src, pix_id);
    uvec4 col_dst = imageLoad(dst, pix_id);

    float src_a = float(col_src.a) / float(0xff);

    uvec4 col = uvec4(col_src * src_a + col_dst * (1 - src_a));

    if (col_dst.a == 0x00) {
        col.a = col_src.a;
    } else {
        col.a = col_src.a + col_dst.a * int(1 - src_a);
    }

    imageStore(dst, pix_id, col);
}
